version: '3'

services:

  backend-kupoday:
    container_name: backend-kupoday
    build: 
      context: backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"      
    restart: always
    depends_on:
      - db-kupoday

  frontend-kupoday:
    container_name: frontend-kupoday
    build: 
      context: frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend-kupoday
  
  db-kupoday:
    container_name: db-kupoday
    image: postgres:12.15-alpine
    env_file:
      - .env
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db-kupoday